# Dependencies
markdown: kramdown
pygments: true
#timezone: Asia/Shanghai

permalink: pretty

# Site Info
title: "NDArray:"
tagline: 'A headers only template library based on meta programming'

url: https://lijiansong.github.io/ndarray
baseurl: /ndarray

github:
  repo: https://github.com/lijiansong/ndarray

encoding: utf-8

author:
  name:           'Json Lee'
  description: 'NDArray is a headers only C++11 template library for N dimensions tensor expressions.'
  url:             https://lijiansong.github.io/ndarray

# Site configurations

paginate: 5
#gems:
#  - jekyll-paginate

version: 1.0.0

