# Dependencies
markdown: kramdown
pygments: true
timezone: Asia/Shanghai
#permalink: /:year-:month-:day.html
permalink: pretty

# Site Info
title: "NDArray:"
tagline: 'A headers only C++11 template library based on meta programming'
baseurl: /ndarray
url: http://lijiansong.github.io/ndarray

github:
  repo: https://github.com/lijiansong/ndarray

encoding: utf-8

author:
  name:           'Json Lee'
  description: 'NDArray is a headers only C++11 template library for N dimensions tensor expressions.'
  url:             https://lijiansong.github.io/ndarray

# Site configurations
gems:
  - jekyll-paginate

version: 1.0.0

